### ISSUE TITLE
Building for iOS fails

### ISSUE THREAD

**Issue by infixlabs** [somedeveloper00/UnityTodo#4]
With this error:

NullReferenceException: Object reference not set to an instance of an object
UnityTodo.ExposedReorderableList.InvokeInternal (System.String methodName, System.Object[] args) (at Assets/Plugins/UnityTodo-main/Editor/ExposedReorderableList.cs:18)
UnityTodo.ExposedReorderableList.ClearCache () (at Assets/Plugins/UnityTodo-main/Editor/ExposedReorderableList.cs:14)
UnityTodo.TaskList+Editor.OnInspectorGUI () (at Assets/Plugins/UnityTodo-main/Editor/TaskList.cs:279)
UnityTodo.TodoWindow.drawTask (System.ValueTuple`2[T1,T2] task) (at Assets/Plugins/UnityTodo-main/Editor/TodoWindow.cs:254)
UnityTodo.TodoWindow.OnGUI () (at Assets/Plugins/UnityTodo-main/Editor/TodoWindow.cs:90)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at /Users/bokken/build/output/unity/unity/Editor/Mono/HostView.cs:512)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at /Users/bokken/build/output/unity/unity/Editor/Mono/GUI/DockArea.cs:386)
UnityEditor.DockArea.OldOnGUI () (at /Users/bokken/build/output/unity/unity/Editor/Mono/GUI/DockArea.cs:377)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:376)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:676)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:536)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Renderer/UIRenderer/UIRenderers.cs:130)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Renderer/UIRRenderChain.cs:514)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Renderer/UIRRepaintUpdater.cs:79)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/VisualTreeUpdater.cs:111)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Panel.cs:1026)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Panel.cs:1087)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:454)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:205)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:74)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:28)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:190)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:190)

**Comment by somedeveloper00** [comment]
~~The stacktrace points to `ReorderableList` not having the method `ClearCache` inside it. Can I ask which Unity version you're using?~~

edit: the problem was related to internal API changes inside Unity's ReorderableList. It's [fixed](https://github.com/somedeveloper00/UnityTodo/commit/e0cc79aaed52c8d415985ea55b2272a2bb8d6689) along with a huge update that turns the project into a simple Unity Package (along with many improvements). I've also updated the README on the main page, you can take a look for instructions; I highly suggest that you use this as a Unity Package and keep updated

**Comment by infixlabs** [comment]
Very nice. Just tested and works great in Unity 2022.3.0f1

**Comment by somedeveloper00** [comment]
Good to know it's working well! I'll close the issue then 👍
